### ISSUE TITLE
Add UbuCon Asia 2025 on ubucon.org

### ISSUE THREAD

**Issue by sukso96100** [ubucon-asia/organizer-tasks#1]
Open PR on https://github.com/aaronprisk/ubucon.org to add UbuCon Asia 2025 on ubucon.org

**Comment by sukso96100** [comment]
Testing matrix integration...

**Comment by Sailesh-Singh** [comment]
Hi @sukso96100,

Would it be okay if I push an update with the estimated date for UbuCon Asia 2025 for now? Once the event details are confirmed, I can update it again to reflect the finalized information.

Let me know if this approach works!

**Comment by sukso96100** [comment]
Surely, sounds like no problem :)

**Comment by Sailesh-Singh** [comment]
I’ve created a Pull Request to add **UbuCon Asia 2025** to [ubucon.org](https://github.com/aaronprisk/ubucon.org). The event details, including date, location, and URL, have been added.  

PR Link: [Add UbuCon Asia 2025](https://github.com/aaronprisk/ubucon.org/pull/3)  

Now awaiting review and merge.

**Comment by sukso96100** [comment]
Thanks :) I guess repo maintainer will review it later. btw, the date (Sep 15 Monday) seem to be on weekdays? Is that for day trip or conference schedule?

**Comment by Sailesh-Singh** [comment]
September 15 is estimated day, i.e mid of September. We will update it when exact date is fixed.

**Comment by sukso96100** [comment]
@Sailesh-Singh Now that we confirmed date, could you submit another PR to update date on ubucon.org?

**Comment by Sailesh-Singh** [comment]
Sure, I will update it. No worries.

**Comment by Sailesh-Singh** [comment]
@sukso96100,  
I have updated the date for **UbuCon Asia 2025** on [ubucon.org](https://github.com/aaronprisk/ubucon.org). The event details, including the updated date, location, and URL, have been added.  

**PR Link**: [https://github.com/aaronprisk/ubucon.org/pull/4](https://github.com/aaronprisk/ubucon.org/pull/4)  

Once the PR is accepted and merged, we can close this issue.
