### ISSUE TITLE
Setup website domain for 2025

### ISSUE THREAD

**Issue by sukso96100** [ubucon-asia/organizer-tasks#2]
@fenris 
Please setup website domain for 2025 as below.

- Domain: 2025.ubucon.asia
- Record type: A
- Addresses:
  - 185.199.108.153
  - 185.199.109.153
  - 185.199.110.153
  - 185.199.111.153

**Comment by fenris** [comment]
Added the DNS A record as per attached screenshot

![Screenshot_20241122_153203](https://github.com/user-attachments/assets/da3157b8-0b5a-4ec6-87e2-d70c5bd2ef77)
